- project:
    templates:
      - openstack-cover-jobs
      - openstack-python3-yoga-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - openstackclient-plugin-jobs
    check:
      jobs:
        - watcherclient-tempest-functional
