- project:
    check:
      jobs:
        - watcherclient-tempest-functional
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - watcherclient-tempest-functional
        - openstack-tox-lower-constraints
