- project:
    templates:
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - openstackclient-plugin-jobs
    check:
      jobs:
        - watcherclient-tempest-functional:
            voting: false
